### PR TITLE
Super big

### PR DESCRIPTION
**Pull request by rnbatra**
Super Big HDF5 processing

For some functions added support for 
 - Chunk processing (memory efficiency)
 - Parallel processing (time efficiency)

Other general code revisions and features.

### CODE REVIEW

**Comment by rnbatra** [comment]
Yes. This should be possible. I’ll have a look.



On 8 Jul 2020, at 13:20, Anand Mayakonda <notifications@github.com> wrote:

﻿

@PoisonAlien requested changes on this pull request.

Thanks Raj for detailed and impressive checks.

One important thing to avoid is using packages from tidyverse as they add up significantly to the package dependancies (data.table on the contrary has no dependancies at all).
I see that you are using strgr, plyrages, dplyr, and magritr. Can you use the corresponding data.table functions instead wherever possible?
Lower the number of dependancies, easier the package maintenance.

**Comment by rnbatra** [comment]
Done. only one function 'get_region_summary' used tidyverse packages. so changed as requested.

However, I would say that there are a few instances where I had changed the data.table consistency to GRanges - and this might be a bit more difficult to tease out. Although I think you use GenomicRanges anyway as a dependency so hope that doesn't spoil the data.table party too much :)

**Comment by PoisonAlien** [comment]
Hi Raj,
Once again thanks. One last thing, could you please run the following commands and make sure there are no errors or warnings? These should be run from `methrix` directory.

```r
devtools::document() #Updated documentation
devtools::build_vignettes() #Builds vignette 
devtools::check() #Check for warnings, errors, and notes
```

`devtools::check()` should not result in any `warnings` or `errors`. `Notes` are accepted.
After the checks, I think it should be safe to merge.

**Comment by rnbatra** [comment]
Hey Anand, I did devtools::check() and got 1-2 warnings and 4 notes, but I think this is what we get on the master as well (I did a quick check). Could you check the master build and let me know?

**Comment by PoisonAlien** [comment]
No problem. Thanks for doing it. `SummarizedExperiment` based packages always struggle with checks. I will take a look..

**Pull request merged**
